name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install
        run: |
          npm install
          npm install -g firebase-tools
      - name: lint and test
        run: |
          npm run lint
          # npm run test
      - run: |
          npm run build:prod
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY_PROD }}
          VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN_PROD }}
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID_PROD }}
          VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET_PROD }}
          VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID_PROD }}
          VITE_APP_ID: ${{ secrets.VITE_APP_ID_PROD }}
          VITE_VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID_PROD }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MINSTA_6885E }}'
          channelId: live
          projectId: minsta-6885e
